### ISSUE TITLE
No warning "No dependencies found, plugin will not run" if not needed

### ISSUE THREAD

**Issue by donaldpipowitch** [bholloway/omit-tilde-webpack-plugin#4]
I'd expect to see the warning `"No dependencies found, plugin will not run"` if I set `include: [ 'package.json' ]` and don't have a `package.json`, but I don't want to see the same warning, when I don't have any dependencies set yet.

Use case are generic build scripts and boilerplates, which don't preconfigure any dependencies, but use this plugin. I don't want a warning when everything works as expected.

**Comment by bholloway** [comment]
Yes @donaldpipowitch, that would be annoying.

I think newbes should get warned by default. However you should be able to opt out of the warning for use cases such as yours.

However a good solution to #1 and #5 should make this whole thing defunct. If you don't need to specify `include`s then you don't need to warn.

**Comment by bholloway** [comment]
closed by #6
